apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-app
spec:
  storageClassName: ""
  volumeName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi